### ISSUE TITLE
automatically chunk uploads

### ISSUE THREAD

**Issue by vanatteveldt** [ccs-amsterdam/amcat4r#1]

**Comment by JBGruber** [comment]
This also prevents errors on large uploads. When data is converted to a json string before upload, the resulting string might be extremely large if there are many documents uploaded at the same time, resulting in `R character strings are limited to 2^31-1 bytes` errors.

**Comment by JBGruber** [comment]
I set the default chunk size to 10,000 after a bit of benchmarking with a 500,000 document upload. It only adds ~1 second to the total time (35 seconds) and I assume it is still reasonably safe for uploads. Smaller sizes like 1000 could work even better with unstable connections to the db etc. but make things considerably slower.
